tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef
credentials-file: /cloudflared/6ff42ae2-765d-4adf-8112-31c55c1551ef.json

ingress:
  - hostname: headscale.replace.me
    service: http://nginx:80
  - hostname: headscale.replace.me
    service: https://nginx:443
  - service: http_status:404